# Generated by Django 4.0 on 2022-11-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
