# Generated by Django 4.0 on 2022-12-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
