# Generated by Django 4.0 on 2022-12-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0010_news_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
    ]
