# Generated by Django 4.0 on 2022-12-21 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0012_news_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
    ]
